#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.0.3 effective-5.10 (swiftlang-6.0.3.1.10 clang-1600.0.30.1)
#ifndef ZGRIMSDK_SWIFT_H
#define ZGRIMSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreData;
@import Foundation;
@import ObjectiveC;
@import UIKit;
@import UserNotifications;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="ZGRImSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class NSString;

@interface NSDictionary<KeyType, ObjectType> (SWIFT_EXTENSION(ZGRImSDK))
- (NSString * _Nullable)zgr_stringValueForKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (NSArray<NSDictionary *> * _Nullable)zgr_dictionaryForKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (id _Nullable)zgr_jsonForKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
@end


@interface NSNotification (SWIFT_EXTENSION(ZGRImSDK))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull zgrDeviceTokenUpdated;)
+ (NSNotificationName _Nonnull)zgrDeviceTokenUpdated SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull zgrDidReceiveRemoteNotification;)
+ (NSNotificationName _Nonnull)zgrDidReceiveRemoteNotification SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull zgrDidOpenRemoteNotification;)
+ (NSNotificationName _Nonnull)zgrDidOpenRemoteNotification SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSNotificationName _Nonnull zgrDidLaunchAppFromRemoteNotification;)
+ (NSNotificationName _Nonnull)zgrDidLaunchAppFromRemoteNotification SWIFT_WARN_UNUSED_RESULT;
@end


@interface UIDevice (SWIFT_EXTENSION(ZGRImSDK))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull zgr_modelName;)
+ (NSString * _Nonnull)zgr_modelName SWIFT_WARN_UNUSED_RESULT;
@end

@class UNNotificationResponse;

SWIFT_CLASS("_TtC8ZGRImSDK9ZGRAction")
@interface ZGRAction : NSObject
@property (nonatomic, copy) NSString * _Nonnull identifier;
@property (nonatomic, copy) NSString * _Nonnull title;
@property (nonatomic, copy) NSString * _Nonnull urlString;
@property (nonatomic, readonly, copy) NSString * _Nullable rawType;
- (nullable instancetype)initWithIdentifier:(NSString * _Nonnull)identifier title:(NSString * _Nonnull)title urlString:(NSString * _Nonnull)urlString OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithDictionary:(NSDictionary * _Nonnull)dictionary;
- (nullable instancetype)initWithResponse:(UNNotificationResponse * _Nonnull)response;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSEntityDescription;
@class NSManagedObjectContext;

SWIFT_CLASS_NAMED("ZGRActionEntity")
@interface ZGRActionEntity : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class ZGRNotificationEntity;

@interface ZGRActionEntity (SWIFT_EXTENSION(ZGRImSDK))
@property (nonatomic, copy) NSString * _Nullable identifier;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, copy) NSString * _Nullable urlString;
@property (nonatomic, strong) ZGRNotificationEntity * _Nullable notification;
@end

typedef SWIFT_ENUM(NSInteger, ZGRActionType, open) {
  ZGRActionTypeDefault = 0,
  ZGRActionTypeDismiss = 1,
  ZGRActionTypeOther = 2,
};

@class NSData;

SWIFT_CLASS("_TtC8ZGRImSDK8ZGRCache")
@interface ZGRCache : NSObject
- (nonnull instancetype)initWithPath:(NSString * _Nonnull)path OBJC_DESIGNATED_INITIALIZER;
- (NSData * _Nullable)dataFromFile:(NSString * _Nonnull)filename SWIFT_WARN_UNUSED_RESULT;
- (void)writeToFile:(NSString * _Nonnull)filename data:(NSData * _Nullable)data;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSURL;

SWIFT_CLASS("_TtC8ZGRImSDK9ZGRConfig")
@interface ZGRConfig : NSObject
@property (nonatomic, copy) NSString * _Nonnull applicationId;
@property (nonatomic, copy) NSString * _Nonnull apiKey;
@property (nonatomic, copy) NSURL * _Nullable endpoint;
@property (nonatomic) BOOL isLocalDatabaseEnabled;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ZGRConfig * _Nonnull sharedInstance;)
+ (ZGRConfig * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (void)resetToEmbeddedConfig;
- (NSString * _Nonnull)getSDKVersion SWIFT_WARN_UNUSED_RESULT;
@end

enum ZGRContentType : NSInteger;

/// @brief Notification media content.
SWIFT_CLASS("_TtC8ZGRImSDK10ZGRContent")
@interface ZGRContent : NSObject
@property (nonatomic, copy) NSURL * _Nullable url;
@property (nonatomic, readonly, copy) NSString * _Nullable rawType;
- (nullable instancetype)initWithUrl:(NSURL * _Nonnull)url type:(enum ZGRContentType)type OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithUserInfo:(NSDictionary * _Nonnull)userInfo;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("ZGRContentEntity")
@interface ZGRContentEntity : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface ZGRContentEntity (SWIFT_EXTENSION(ZGRImSDK))
@property (nonatomic, copy) NSString * _Nullable type;
@property (nonatomic, copy) NSURL * _Nullable url;
@property (nonatomic, strong) ZGRNotificationEntity * _Nullable notification;
@end

typedef SWIFT_ENUM(NSInteger, ZGRContentType, open) {
  ZGRContentTypeNone = 0,
  ZGRContentTypeHtml = 1,
  ZGRContentTypeImage = 2,
  ZGRContentTypeOther = 3,
};

@class ZGRDatabase;
@class ZGRNotification;
@class ZGRDatabaseRequest;

SWIFT_PROTOCOL("_TtP8ZGRImSDK19ZGRDatabaseProtocol_")
@protocol ZGRDatabaseProtocol <NSObject>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ZGRDatabase * _Nullable sharedInstance;)
+ (ZGRDatabase * _Nullable)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (NSArray<ZGRNotification *> * _Nullable)allNotifications SWIFT_WARN_UNUSED_RESULT;
- (NSArray<ZGRNotification *> * _Nullable)notificationsWith:(ZGRDatabaseRequest * _Nonnull)request SWIFT_WARN_UNUSED_RESULT;
- (void)deleteAllNotifications;
- (void)addNotification:(ZGRNotification * _Nonnull)notification;
- (void)deleteNotification:(ZGRNotification * _Nonnull)notification;
- (void)updateNotification:(NSString * _Nonnull)identifier status:(NSString * _Nonnull)status;
- (NSString * _Nullable)getInstallationId SWIFT_WARN_UNUSED_RESULT;
- (void)saveInstallationId:(NSString * _Nonnull)installationId;
- (void)deleteNotificationsArray:(NSArray<ZGRNotification *> * _Nonnull)array;
@end


SWIFT_CLASS("_TtC8ZGRImSDK11ZGRDatabase")
@interface ZGRDatabase : NSObject <ZGRDatabaseProtocol>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ZGRDatabase * _Nullable sharedInstance;)
+ (ZGRDatabase * _Nullable)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (void)setPersistentContainerNil;
- (NSArray<ZGRNotification *> * _Nullable)allNotifications SWIFT_WARN_UNUSED_RESULT;
- (NSArray<ZGRNotification *> * _Nullable)notificationsWith:(ZGRDatabaseRequest * _Nonnull)request SWIFT_WARN_UNUSED_RESULT;
- (void)deleteAllNotifications;
- (void)addNotification:(ZGRNotification * _Nonnull)notification;
- (void)deleteNotification:(ZGRNotification * _Nonnull)notification;
- (void)deleteNotificationsArray:(NSArray<ZGRNotification *> * _Nonnull)array;
- (void)updateNotification:(NSString * _Nonnull)identifier status:(NSString * _Nonnull)status;
- (NSString * _Nullable)getInstallationId SWIFT_WARN_UNUSED_RESULT;
- (void)saveInstallationId:(NSString * _Nonnull)installationId;
@end


@class NSDate;

SWIFT_CLASS("_TtC8ZGRImSDK18ZGRDatabaseRequest")
@interface ZGRDatabaseRequest : NSObject
@property (nonatomic) NSUInteger fetchLimit;
@property (nonatomic) NSUInteger pageOffset;
@property (nonatomic, copy) NSDate * _Nullable fromDate;
@property (nonatomic, copy) NSDate * _Nullable toDate;
@property (nonatomic, copy) NSString * _Nullable status;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSCoder;

SWIFT_CLASS("_TtC8ZGRImSDK8ZGRError")
@interface ZGRError : NSError
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSErrorDomain _Nonnull ZGRErrorDomain;)
+ (NSErrorDomain _Nonnull)ZGRErrorDomain SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithDomain:(NSString * _Nonnull)domain code:(NSInteger)code userInfo:(NSDictionary<NSString *, id> * _Nullable)dict OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, ZGRErrorCode, closed) {
  ZGRErrorCodeLocalDatabaseNotEnabled = 0,
  ZGRErrorCodeJSONDeserializationError = 1,
};

@class ZGRSubscription;

SWIFT_CLASS("_TtC8ZGRImSDK15ZGRInstallation")
@interface ZGRInstallation : NSObject
@property (nonatomic) BOOL isPrimary;
@property (nonatomic) BOOL isPushOsEnabled;
@property (nonatomic) BOOL isPushEnabled;
@property (nonatomic, copy) NSArray<ZGRSubscription *> * _Nonnull subscriptions;
- (nullable instancetype)initWithJSON:(NSString * _Nonnull)JSON error:(ZGRError * _Nullable)error;
- (nullable instancetype)initWithJSONData:(NSData * _Nonnull)JSONData error:(ZGRError * _Nullable)error;
- (nullable instancetype)initWithDictionary:(NSDictionary * _Nonnull)dictionary error:(NSError * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("ZGRInstallationEntity")
@interface ZGRInstallationEntity : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end


@interface ZGRInstallationEntity (SWIFT_EXTENSION(ZGRImSDK))
@property (nonatomic, copy) NSString * _Nullable identifier;
@end

@protocol ZGRNetworkProtocol;

SWIFT_CLASS("_TtC8ZGRImSDK12ZGRMessaging")
@interface ZGRMessaging : NSObject
@property (nonatomic, strong) id <ZGRNetworkProtocol> _Nullable network;
@property (nonatomic, strong) id <ZGRDatabaseProtocol> _Nullable database;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ZGRMessaging * _Nonnull shared;)
+ (ZGRMessaging * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
+ (ZGRMessaging * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@property (nonatomic, strong) ZGRConfig * _Nonnull config;
@property (nonatomic, copy) NSString * _Nonnull deviceId;
@property (nonatomic, readonly, copy) NSString * _Nonnull installationId;
@end

@class ZGRUser;

@interface ZGRMessaging (SWIFT_EXTENSION(ZGRImSDK))
- (void)personalize:(NSString * _Nonnull)externalUserId withCompletionHandler:(void (^ _Nonnull)(ZGRUser * _Nullable, ZGRError * _Nullable))completionHandler;
- (void)depersonalizeWithCompletionHandler:(void (^ _Nonnull)(void))completionHandler;
@end


@interface ZGRMessaging (SWIFT_EXTENSION(ZGRImSDK))
- (void)fetchInstallationWithCompletionHandler:(void (^ _Nonnull)(ZGRInstallation * _Nullable, ZGRError * _Nullable))completionHandler;
- (void)save:(ZGRInstallation * _Nonnull)installation withCompletionHandler:(void (^ _Nonnull)(void))completionHandler;
@end



@interface ZGRMessaging (SWIFT_EXTENSION(ZGRImSDK))
- (void)fetchUserWithCompletionHandler:(void (^ _Nonnull)(ZGRUser * _Nullable, ZGRError * _Nullable))completionHandler;
- (BOOL)saveUserWithPhoneNumber:(NSString * _Nonnull)phoneNumber withCompletionHandler:(void (^ _Nonnull)(ZGRUser * _Nullable, ZGRError * _Nullable))completionHandler SWIFT_WARN_UNUSED_RESULT;
- (BOOL)saveUserWithPhoneNumber:(NSString * _Nonnull)phoneNumber externalUserId:(NSString * _Nonnull)externalUserId withCompletionHandler:(void (^ _Nonnull)(ZGRUser * _Nullable, ZGRError * _Nullable))completionHandler SWIFT_WARN_UNUSED_RESULT;
@end


@interface ZGRMessaging (SWIFT_EXTENSION(ZGRImSDK))
@property (nonatomic) BOOL isLocalDatabaseEnabled;
- (void)fetchAllNotifications:(void (^ _Nonnull)(NSArray<ZGRNotification *> * _Nullable, ZGRError * _Nullable))completionHandler;
- (void)fetchNotificationsWith:(ZGRDatabaseRequest * _Nonnull)request completionHandler:(void (^ _Nonnull)(NSArray<ZGRNotification *> * _Nullable, ZGRError * _Nullable))completionHandler;
- (void)delete:(ZGRNotification * _Nonnull)notification withCompletionHandler:(void (^ _Nonnull)(BOOL, ZGRError * _Nullable))completionHandler;
- (void)deleteNotificationsArray:(NSArray<ZGRNotification *> * _Nonnull)array withCompletionHandler:(void (^ _Nonnull)(BOOL, ZGRError * _Nullable))completionHandler;
- (void)updateNotification:(ZGRNotification * _Nonnull)notification status:(NSString * _Nonnull)stat withCompletionHandler:(void (^ _Nonnull)(BOOL, ZGRError * _Nullable))completionHandler;
@end

@class UIApplication;
@class UNUserNotificationCenter;
@class UIViewController;

@interface ZGRMessaging (SWIFT_EXTENSION(ZGRImSDK))
- (void)registerForRemoteNotifications:(NSData * _Nonnull)forRemoteNotifications;
- (BOOL)application:(UIApplication * _Nonnull)application didReceiveRemoteNotification:(NSDictionary * _Nonnull)userInfo withCompletionHandler:(SWIFT_NOESCAPE void (^ _Nonnull)(ZGRNotification * _Nonnull))completionHandler SWIFT_WARN_UNUSED_RESULT;
- (BOOL)userNotificationCenter:(UNUserNotificationCenter * _Nonnull)center didReceive:(UNNotificationResponse * _Nonnull)response withCompletionHandler:(void (^ _Nullable)(ZGRNotification * _Nonnull, ZGRAction * _Nonnull))completionHandler SWIFT_WARN_UNUSED_RESULT;
- (BOOL)notificationCenter:(UNUserNotificationCenter * _Nonnull)center didReceive:(UNNotificationResponse * _Nonnull)response withCompletionHandler:(void (^ _Nullable)(ZGRNotification * _Nonnull, ZGRAction * _Nonnull))completionHandler SWIFT_WARN_UNUSED_RESULT;
- (void)showLinkPageWith:(NSURL * _Nonnull)url andViewController:(UIViewController * _Nonnull)vc;
- (void)application:(UIApplication * _Nonnull)application setApplicationBadgeNumber:(NSInteger)num;
- (void)updateNotificationStatus:(NSString * _Nonnull)status forNotification:(NSString * _Nonnull)identifier;
- (void)checkSeensAndUpdateNotificationStatus;
- (void)checkIsPushGranted;
@end

@class ZGRNetworkRequest;

SWIFT_PROTOCOL("_TtP8ZGRImSDK18ZGRNetworkProtocol_")
@protocol ZGRNetworkProtocol <NSObject>
@property (nonatomic, strong) ZGRCache * _Nullable cache;
- (void)enqueueRequest:(ZGRNetworkRequest * _Nonnull)request;
- (void)enqueueRequest:(ZGRNetworkRequest * _Nonnull)request completionHandler:(void (^ _Nullable)(NSData * _Nullable, NSError * _Nullable))completion;
@end


SWIFT_CLASS("_TtC8ZGRImSDK10ZGRNetwork")
@interface ZGRNetwork : NSObject <ZGRNetworkProtocol>
@property (nonatomic, strong) ZGRCache * _Nullable cache;
- (nonnull instancetype)initWithCache:(ZGRCache * _Nonnull)cache OBJC_DESIGNATED_INITIALIZER;
- (void)enqueueRequest:(ZGRNetworkRequest * _Nonnull)request;
- (void)enqueueRequest:(ZGRNetworkRequest * _Nonnull)request completionHandler:(void (^ _Nullable)(NSData * _Nullable, NSError * _Nullable))completion;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC8ZGRImSDK17ZGRNetworkRequest")
@interface ZGRNetworkRequest : NSObject <NSCoding>
@property (nonatomic, copy) NSString * _Nullable category;
@property (nonatomic, copy) NSURL * _Nullable url;
@property (nonatomic, copy) NSString * _Nullable method;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable headers;
@property (nonatomic, copy) NSData * _Nullable body;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)decoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * _Nonnull)coder;
- (void)setValue:(NSString * _Nullable)value forHTTPHeader:(NSString * _Nonnull)header;
- (void)setHTTPHeaders:(NSDictionary<NSString *, id> * _Nonnull)req;
- (NSString * _Nonnull)requestDebugDescription SWIFT_WARN_UNUSED_RESULT;
@end

@class ZGRNetworkRequestParams;

@interface ZGRNetworkRequest (SWIFT_EXTENSION(ZGRImSDK))
+ (ZGRNetworkRequest * _Nullable)prepareRequest:(ZGRNetworkRequestParams * _Nonnull)requestParams SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC8ZGRImSDK26ZGRNetworkRequestOperation")
@interface ZGRNetworkRequestOperation : NSOperation
@property (nonatomic, readonly, getter=isAsynchronous) BOOL asynchronous;
@property (nonatomic, readonly, getter=isExecuting) BOOL executing;
@property (nonatomic, readonly, getter=isFinished) BOOL finished;
- (void)start;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC8ZGRImSDK23ZGRNetworkRequestParams")
@interface ZGRNetworkRequestParams : NSObject
- (nonnull instancetype)initWithJs:(NSData * _Nullable)js path:(NSString * _Nonnull)path cat:(NSString * _Nonnull)cat mtd:(NSString * _Nonnull)mtd OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UNNotificationContent;

/// @brief Notification info.
SWIFT_CLASS("_TtC8ZGRImSDK15ZGRNotification")
@interface ZGRNotification : NSObject
@property (nonatomic, copy) NSString * _Nonnull identifier;
@property (nonatomic, copy) NSDate * _Nonnull date;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable subtitle;
@property (nonatomic, copy) NSString * _Nullable text;
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, copy) NSString * _Nullable urlString;
@property (nonatomic, strong) ZGRContent * _Nullable content;
@property (nonatomic, copy) NSArray<ZGRAction *> * _Nullable actions;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable extraOptions;
@property (nonatomic) id _Nullable customPayload;
- (nullable instancetype)initWithContent:(UNNotificationContent * _Nonnull)content OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithRemoteNotification:(NSDictionary * _Nonnull)remoteNotification OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNotificationEntity:(ZGRNotificationEntity * _Nonnull)notificationEntity OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UIView;
@class UNNotification;
@class UNNotificationAction;

SWIFT_CLASS("_TtC8ZGRImSDK22ZGRNotificationContent")
@interface ZGRNotificationContent : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) ZGRNotificationContent * _Nonnull shared;)
+ (ZGRNotificationContent * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
+ (ZGRNotificationContent * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (void)didLoad:(UIView * _Nonnull)view;
- (void)contentPresentationEnded;
- (void)didReceive:(UNNotification * _Nonnull)unNotification completionHandler:(void (^ _Nonnull)(NSArray<UNNotificationAction *> * _Nullable))completionHandler;
- (BOOL)isZGRNotification:(NSDictionary * _Nonnull)userInfo SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("ZGRNotificationEntity")
@interface ZGRNotificationEntity : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end

@class NSSet;

@interface ZGRNotificationEntity (SWIFT_EXTENSION(ZGRImSDK))
- (void)addActionsObject:(ZGRActionEntity * _Nonnull)value;
- (void)removeActionsObject:(ZGRActionEntity * _Nonnull)value;
- (void)addActions:(NSSet * _Nonnull)values;
- (void)removeActions:(NSSet * _Nonnull)values;
@end


@interface ZGRNotificationEntity (SWIFT_EXTENSION(ZGRImSDK))
@property (nonatomic, copy) NSData * _Nullable customPayload;
@property (nonatomic, copy) NSDate * _Nullable date;
@property (nonatomic, copy) NSString * _Nullable identifier;
@property (nonatomic, copy) NSString * _Nullable status;
@property (nonatomic, copy) NSString * _Nullable subtitle;
@property (nonatomic, copy) NSString * _Nullable text;
@property (nonatomic, copy) NSString * _Nullable title;
@property (nonatomic, copy) NSString * _Nullable urlString;
@property (nonatomic, strong) NSSet * _Nullable actions;
@property (nonatomic, strong) ZGRContentEntity * _Nullable content;
@end


SWIFT_CLASS("_TtC8ZGRImSDK22ZGRNotificationService")
@interface ZGRNotificationService : UNNotificationServiceExtension
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSManagedObjectModel;

SWIFT_CLASS("_TtC8ZGRImSDK22ZGRPersistentContainer")
@interface ZGRPersistentContainer : NSPersistentContainer
+ (NSURL * _Nonnull)defaultDirectoryURL SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithName:(NSString * _Nonnull)name managedObjectModel:(NSManagedObjectModel * _Nonnull)model OBJC_DESIGNATED_INITIALIZER;
@end

@class NSNumber;

SWIFT_CLASS("_TtC8ZGRImSDK15ZGRSubscription")
@interface ZGRSubscription : NSObject
@property (nonatomic, strong) NSNumber * _Nullable identifier;
@property (nonatomic, readonly, copy) NSString * _Nullable rawType;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull title;
@property (nonatomic, copy) NSString * _Nonnull desc;
@property (nonatomic, copy) NSString * _Nonnull value;
@property (nonatomic, readonly, strong) NSDictionary * _Nonnull dictionary;
- (nullable instancetype)initWithJSON:(NSString * _Nonnull)JSON error:(ZGRError * _Nullable)error;
- (nullable instancetype)initWithJSONData:(NSData * _Nonnull)JSONData error:(ZGRError * _Nullable)error;
- (nullable instancetype)initWithDictionary:(NSDictionary * _Nonnull)dictionary error:(ZGRError * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
/// < Returns failure for ZGRSubscriptionTypeSetting
- (BOOL)setValueWithBool:(BOOL)value SWIFT_WARN_UNUSED_RESULT;
/// < Returns failure for ZGRSubscriptionTypePermission
- (BOOL)setValueWithString:(NSString * _Nonnull)value SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, ZGRSubscriptionType, open) {
  ZGRSubscriptionTypeSettings = 0,
  ZGRSubscriptionTypePermission = 1,
};


SWIFT_CLASS("_TtC8ZGRImSDK7ZGRUser")
@interface ZGRUser : NSObject
@property (nonatomic, copy) NSString * _Nullable externalUserId;
@property (nonatomic, copy) NSString * _Nullable phoneNumber;
- (nullable instancetype)initWithJSON:(NSString * _Nonnull)JSON error:(ZGRError * _Nullable)error;
- (nullable instancetype)initWithJSONData:(NSData * _Nonnull)JSONData error:(ZGRError * _Nullable)error;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
